import { useState } from 'react'
import { ActionForm } from './action-form'
import { Field, Input, Select } from './ui/form-controls'
import { useClinic } from '@/state/clinic-store'
import { roleNames, type Membership } from '@/domain/types'
import { membershipsFor } from '@/domain/access'

export function AccessForm({ centerId, platform = false }: { centerId: string; platform?: boolean }) {
  const { assignAccess, data, user } = useClinic(); const [role, setRole] = useState<Membership['role']>('ADMIN')
  return <div className="grid gap-5"><p className="text-sm text-muted-foreground">Para actualizar una cuenta existente, usa su correo. La contraseña solo se requiere para cuentas nuevas. Las cuentas de pacientes se originan en su registro y se muestran aquí sin exponer su ficha clínica.</p><ActionForm reset={false} className="sm:grid-cols-2" label="Guardar acceso" onSave={(v) => assignAccess(v.email, v.name, { organizationId: centerId, role: platform ? 'ADMIN' : role, professionalId: v.professionalId, extraPermissions: v.upload === 'on' ? ['results.upload'] : [] }, v.password)}><Field label="Nombre del usuario"><Input name="name" required /></Field><Field label="Correo de la cuenta"><Input name="email" type="email" required /></Field>{!platform && <Field label="Rol en este centro"><Select value={role} onChange={(e) => setRole(e.target.value as Membership['role'])}>{(['ADMIN', 'RECEPCIONISTA', 'PROFESIONAL'] as const).map((r) => <option key={r} value={r}>{roleNames[r]}</option>)}</Select></Field>}<Field label="Contraseña inicial (solo cuenta nueva)"><Input type="password" name="password" autoComplete="new-password" placeholder="8 caracteres, mayúscula, minúscula y número" /></Field>{role === 'PROFESIONAL' && <Field label="Ficha del profesional"><Select name="professionalId" required><option value="">Seleccionar</option>{data.professionals.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.email}</option>)}</Select></Field>}{role === 'RECEPCIONISTA' && <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="upload" /> Permitir carga de borradores de informes</label>}</ActionForm><ul className="divide-y text-sm">{data.users.flatMap((u) => membershipsFor(u).filter((m) => m.organizationId === centerId && (!platform || m.role === 'ADMIN')).map((m) => <li className="py-3" key={`${u.id}-${m.organizationId}`}>{u.name} · {u.email}<span className="block text-xs text-muted-foreground">{roleNames[m.role]}{u.id === user?.id ? ' · Tu cuenta' : ''}{m.extraPermissions?.includes('results.upload') ? ' · Puede cargar borradores' : ''}</span></li>))}</ul></div>
}
