import { Navigate } from 'react-router-dom'
import { PageHeading } from '@/components/page-heading'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { StatusBadge } from '@/components/ui/badge'
import { useClinic } from '@/state/clinic-store'

export function AdminPage() {
  const { data, user } = useClinic(); if (user?.role !== 'ADMIN') return <Navigate to="/" replace />
  return <><PageHeading title="Administración" description="Catálogos que luego serán gestionados por la API de Laravel." /><section className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Especialidades</CardTitle><CardDescription>Áreas de atención disponibles.</CardDescription></CardHeader><CardContent className="grid gap-3">{data.specialties.map((s) => <div key={s.id} className="flex items-center justify-between rounded-lg border p-4"><div><p className="font-medium">{s.name}</p><p className="text-xs text-muted-foreground">{s.description}</p></div><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs text-emerald-800">Activa</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Prestaciones</CardTitle><CardDescription>Servicios, especialidad y duración.</CardDescription></CardHeader><CardContent className="grid gap-3">{data.services.map((s) => <div key={s.id} className="flex justify-between rounded-lg border p-4"><div><p className="font-medium">{s.name}</p><p className="text-xs text-muted-foreground">{data.specialties.find((sp) => sp.id === s.specialtyId)?.name}</p></div><strong className="text-sm text-primary">{s.duration} min</strong></div>)}</CardContent></Card><Card className="xl:col-span-2"><CardHeader><CardTitle>Profesionales</CardTitle><CardDescription>Directorio y disponibilidad base.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.professionals.map((p) => <div key={p.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{p.email}</p></div><StatusBadge status="CONFIRMADA" /></div><p className="mt-4 text-xs text-muted-foreground">Lunes a viernes · 09:00–17:00</p></div>)}</div></CardContent></Card></section></>
}
