import { Check, ChevronLeft, ChevronRight } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { PageHeading } from '@/components/page-heading'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, Input, Select, Textarea } from '@/components/ui/form-controls'
import { dateFromToday } from '@/lib/utils'
import { useClinic } from '@/state/clinic-store'
import { toast } from 'sonner'
import { useCenterPath } from '@/lib/tenant'

export function BookingPage() {
  const { data, user, slots, createAppointment } = useClinic(); const navigate = useNavigate(); const centerPath = useCenterPath(); const staff = user?.role === 'RECEPCIONISTA'
  const [step, setStep] = useState(1); const [patientId, setPatientId] = useState(''); const [specialtyId, setSpecialtyId] = useState(''); const [professionalId, setProfessionalId] = useState(''); const [serviceId, setServiceId] = useState(''); const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [note, setNote] = useState(''); const [overbook, setOverbook] = useState(false)
  const professionals = data.professionals.filter((p) => p.active && p.specialtyIds.includes(specialtyId)); const services = data.services.filter((s) => s.active && s.specialtyId === specialtyId)
  const available = useMemo(() => slots(professionalId, serviceId, date), [slots, professionalId, serviceId, date])
  if (!['RECEPCIONISTA', 'PACIENTE'].includes(user?.role ?? '')) return <Navigate to="/" replace />
  const next = () => { if (step === 1 && (!specialtyId || !professionalId || !serviceId || (staff && !patientId))) return; if (step === 2 && (!date || !time)) return; setStep(Math.min(3, step + 1)) }
  const submit = (event: FormEvent) => { event.preventDefault(); try { createAppointment({ patientId: staff ? patientId : undefined, specialtyId, professionalId, serviceId, date, time, note, overbook }); navigate(centerPath('/citas')) } catch (error) { toast.error((error as Error).message) } }
  const selection = `${data.specialties.find((s) => s.id === specialtyId)?.name} · ${data.professionals.find((p) => p.id === professionalId)?.name}`
  return <><PageHeading title="Reservar hora" description="Completa los datos en tres pasos." /><div className="mx-auto mb-8 flex max-w-2xl items-center">{['Atención', 'Horario', 'Confirmación'].map((label, index) => <div key={label} className="contents"><div className="grid justify-items-center gap-2"><span className={`grid size-9 place-items-center rounded-full border-2 text-sm font-bold ${step > index ? 'border-primary bg-primary text-white' : 'border-border bg-background text-muted-foreground'}`}>{step > index + 1 ? <Check className="size-4" /> : index + 1}</span><small className="hidden text-xs font-medium sm:block">{label}</small></div>{index < 2 && <span className={`mb-5 h-0.5 flex-1 ${step > index + 1 ? 'bg-primary' : 'bg-border'}`} />}</div>)}</div>
    <form onSubmit={submit}><Card className="mx-auto max-w-3xl"><CardHeader><CardTitle>{step === 1 ? 'Selecciona la atención' : step === 2 ? 'Elige fecha y horario' : 'Revisa tu reserva'}</CardTitle><CardDescription>{step === 1 ? 'La disponibilidad depende de la prestación y profesional.' : step === 2 ? selection : 'Confirma que los datos sean correctos.'}</CardDescription></CardHeader><CardContent>
      {step === 1 && <div className="grid gap-5 sm:grid-cols-2">{staff && <Field className="sm:col-span-2" label="Paciente"><Select required value={patientId} onChange={(e) => setPatientId(e.target.value)}><option value="">Seleccionar paciente</option>{data.patients.filter((p) => p.active).map((p) => <option key={p.id} value={p.id}>{p.rut} · {p.name}</option>)}</Select></Field>}<Field label="Especialidad"><Select required value={specialtyId} onChange={(e) => { setSpecialtyId(e.target.value); setProfessionalId(''); setServiceId('') }}><option value="">Seleccionar</option>{data.specialties.filter((s) => s.active).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field><Field label="Profesional"><Select required disabled={!specialtyId} value={professionalId} onChange={(e) => setProfessionalId(e.target.value)}><option value="">Seleccionar</option>{professionals.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><Field className="sm:col-span-2" label="Prestación"><Select required disabled={!specialtyId} value={serviceId} onChange={(e) => setServiceId(e.target.value)}><option value="">Seleccionar</option>{services.map((s) => <option key={s.id} value={s.id}>{s.name} · {s.duration} min</option>)}</Select></Field></div>}
      {step === 2 && <div className="grid gap-6"><Field label="Fecha"><Input type="date" min={dateFromToday(1)} value={date} onChange={(e) => { setDate(e.target.value); setTime('') }} required /></Field><div><p className="mb-3 text-sm font-medium">Horarios disponibles</p><div className="flex min-h-16 flex-wrap gap-2 rounded-xl bg-muted/55 p-4">{date && available.map((slot) => <Button type="button" key={slot.time} variant={time === slot.time ? 'default' : 'outline'} size="sm" onClick={() => setTime(slot.time)}>{slot.time}</Button>)}{!date && <p className="text-sm text-muted-foreground">Selecciona una fecha para consultar.</p>}{date && available.length === 0 && <p className="text-sm text-muted-foreground">No hay horas disponibles para este día.</p>}</div></div><Field label="Observación administrativa (opcional)"><Textarea value={note} onChange={(e) => setNote(e.target.value)} maxLength={300} placeholder="No ingresar información clínica." /></Field>{staff && <label className="flex items-start gap-3 rounded-lg bg-amber-50 p-4 text-sm text-amber-900"><input type="checkbox" className="mt-1" checked={overbook} onChange={(e) => setOverbook(e.target.checked)} /> Crear como sobreturno; revisé el impacto en la agenda.</label>}</div>}
      {step === 3 && <dl className="grid gap-5 rounded-xl bg-muted/50 p-5 sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Paciente</dt><dd className="font-medium">{staff ? data.patients.find((p) => p.id === patientId)?.name : user?.name}</dd></div><div><dt className="text-xs text-muted-foreground">Atención</dt><dd className="font-medium">{data.services.find((s) => s.id === serviceId)?.name}</dd></div><div><dt className="text-xs text-muted-foreground">Profesional</dt><dd className="font-medium">{data.professionals.find((p) => p.id === professionalId)?.name}</dd></div><div><dt className="text-xs text-muted-foreground">Fecha y hora</dt><dd className="font-medium">{date} · {time}</dd></div></dl>}
      <div className="mt-7 flex justify-between"><Button type="button" variant="ghost" disabled={step === 1} onClick={() => setStep(step - 1)}><ChevronLeft className="size-4" /> Volver</Button>{step < 3 ? <Button type="button" onClick={next}>Continuar <ChevronRight className="size-4" /></Button> : <Button type="submit">Confirmar reserva</Button>}</div>
    </CardContent></Card></form></>
}
