import { CalendarRange, ChartNoAxesCombined, CircleDollarSign, TrendingDown, UsersRound } from 'lucide-react'
import { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { financeForOrganization, type AppointmentState, type ProfessionalPerformance, type ServicePerformance } from '@/data/clinic-finance-mock'
import { PageHeading } from '@/components/page-heading'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, Input, Select } from '@/components/ui/form-controls'
import { useClinic } from '@/state/clinic-store'

const clp = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 })
const monthLabel = new Intl.DateTimeFormat('es-CL', { month: 'short' })

function Bars({ title, items, value, suffix = '' }: { title: string; items: { label: string; total: number }[]; value: (item: { label: string; total: number }) => string; suffix?: string }) { const max = Math.max(1, ...items.map((item) => item.total)); return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="grid gap-5">{items.length ? items.map((item) => <div key={item.label}><div className="mb-2 flex justify-between gap-3 text-sm"><span>{item.label}</span><strong>{value(item)}{suffix}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${item.total * 100 / max}%` }} /></div></div>) : <p className="text-sm text-muted-foreground">No hay datos para los filtros seleccionados.</p>}</CardContent></Card> }
function RevenueChart({ points }: { points: { month: string; total: number }[] }) { const max = Math.max(1, ...points.map((item) => item.total)); return <Card><CardHeader><CardTitle>Evolución de ingresos estimados</CardTitle></CardHeader><CardContent>{points.length ? <div className="flex h-52 items-end gap-3 border-b pt-5">{points.map((point) => <div className="flex h-full flex-1 flex-col justify-end gap-2 text-center" key={point.month}><span className="text-[11px] font-semibold">{clp.format(point.total)}</span><div className="rounded-t-md bg-primary/85" style={{ height: `${Math.max(8, point.total * 100 / max)}%` }} /><span className="text-xs capitalize text-muted-foreground">{monthLabel.format(new Date(`${point.month}-01T12:00:00`))}</span></div>)}</div> : <p className="py-12 text-center text-sm text-muted-foreground">No hay ingresos para este rango de fechas.</p>}</CardContent></Card> }
function AppointmentStates({ states }: { states: AppointmentState[] }) { const total = states.reduce((sum, state) => sum + state.total, 0); return <Card><CardHeader><CardTitle>Estado de las citas</CardTitle></CardHeader><CardContent>{states.length ? <><div className="flex h-4 overflow-hidden rounded-full bg-muted">{states.map((state) => <div key={state.label} className={state.tone} style={{ width: `${state.total * 100 / Math.max(1, total)}%` }} title={`${state.label}: ${state.total}`} />)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{states.map((state) => <div className="flex items-center justify-between text-sm" key={state.label}><span className="flex items-center gap-2"><i className={`size-2.5 rounded-full ${state.tone}`} />{state.label}</span><strong>{state.total}</strong></div>)}</div></> : <p className="text-sm text-muted-foreground">No hay citas para mostrar.</p>}</CardContent></Card> }

export function ClinicFinancePage({ reports = false }: { reports?: boolean }) {
  const { data, organization, user } = useClinic(); const [from, setFrom] = useState('2026-04-01'); const [to, setTo] = useState('2026-09-30'); const [professionalId, setProfessionalId] = useState(''); const [serviceId, setServiceId] = useState('')
  if (user?.role !== 'ADMIN' || !organization) return <Navigate to="/" replace />
  const finance = financeForOrganization(organization.id), periodRevenue = finance.revenueByMonth.filter((point) => `${point.month}-01` >= from && `${point.month}-01` <= to), serviceRows: ServicePerformance[] = serviceId ? finance.services.filter((item) => item.serviceId === serviceId) : finance.services, professionalRows: ProfessionalPerformance[] = professionalId ? finance.professionals.filter((item) => item.professionalId === professionalId) : finance.professionals, income = periodRevenue.reduce((sum, point) => sum + point.total, 0), attended = finance.appointmentStates.find((state) => state.label === 'Realizadas')?.total ?? 0, cancelled = finance.appointmentStates.find((state) => state.label === 'Canceladas')?.total ?? 0, noShow = finance.appointmentStates.find((state) => state.label === 'No-show')?.total ?? 0, ticket = Math.round(income / Math.max(1, attended))
  const kpis = [{ label: 'Ingresos estimados', value: clp.format(income), Icon: CircleDollarSign }, { label: 'Atenciones realizadas', value: attended, Icon: UsersRound }, { label: 'Ticket promedio', value: clp.format(ticket), Icon: ChartNoAxesCombined }, { label: 'Citas canceladas', value: cancelled, Icon: CalendarRange }, { label: 'No-show y pérdidas', value: `${noShow} · ${clp.format(finance.lostRevenue)}`, Icon: TrendingDown }]
  return <><PageHeading eyebrow="Comercial de la clínica" title={reports ? 'Reportes comerciales' : 'Comercial y finanzas'} description={reports ? `Análisis comercial estimado de ${organization.name}.` : `Indicadores económicos y operacionales estimados de ${organization.name}.`} /><Card className="mb-6"><CardContent className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Desde"><Input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></Field><Field label="Hasta"><Input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></Field><Field label="Profesional"><Select value={professionalId} onChange={(event) => setProfessionalId(event.target.value)}><option value="">Todos los profesionales</option>{data.professionals.map((professional) => <option key={professional.id} value={professional.id}>{professional.name}</option>)}</Select></Field><Field label="Prestación"><Select value={serviceId} onChange={(event) => setServiceId(event.target.value)}><option value="">Todas las prestaciones</option>{data.services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</Select></Field></CardContent></Card>{!reports && <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(({ label, value, Icon }) => <Card key={label}><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs text-muted-foreground">{label}</p><strong className="mt-2 block text-xl">{value}</strong></div><Icon className="size-5 text-primary" /></CardContent></Card>)}</section>}<section className="grid gap-5 xl:grid-cols-2"><RevenueChart points={periodRevenue} /><AppointmentStates states={finance.appointmentStates} /><Bars title="Ingresos por prestación" items={serviceRows.map((item) => ({ label: item.label, total: item.revenue }))} value={(item) => clp.format(item.total)} /><Bars title="Ingresos por profesional" items={professionalRows.map((item) => ({ label: item.label, total: item.revenue }))} value={(item) => clp.format(item.total)} />{reports && <Bars title="Prestaciones más solicitadas" items={serviceRows.map((item) => ({ label: item.label, total: item.bookings }))} value={(item) => String(item.total)} suffix=" reservas" />}<Card><CardHeader><CardTitle>Pérdidas estimadas</CardTitle></CardHeader><CardContent><strong className="text-3xl text-rose-700">{clp.format(finance.lostRevenue)}</strong><p className="mt-3 text-sm text-muted-foreground">Estimación asociada a {cancelled} cancelaciones y {noShow} no-show del período seleccionado.</p></CardContent></Card></section></>
}
